# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

pokemon1 = Pokemon.create! ( { name: "Turtwig", pokemontype: "Grass", region: "Sinnoh", physiology: "Turtwig is a Pokémon and appears to be a green-ish Pokémon with a small twig on its head. On the twig are two green leaves. It has large yellow eyes and its face is oddly shaped. On the bottom of the face there is a yellow mouth in an obtuse shape. Also on its face it has two tiny nostrils. It has four small stubby feet, so it can't move as fast, and on the bottom of its feet are an obtuse area of yellow towards the bottom of the feet. It also has a shell on its back. The shell is brown with black line on the bottom and a few stripes.", special_abilities: "", behavior: "", evolution: "Turtwig evolves into a Grotle starting at level 18, which later evolves into a Torterra starting at level 32." })

pokemon2 = Pokemon.create! ( { name: "Chimchar", pokemontype: "Fire", region: "Unova", physiology: "Chimchar are based on monkeys. Being very agile, Chimchar are able to climb the rocky ledges of tall mountains, where they live. A Chimchar's flame is produced by burning gas in its stomach. Chimchar have a light colored stomach with a little swirl at the top on its chest. The swirl on Chimchar's chest carries over to Monferno and Infernape. The flames do not go out in the rain like the flames on a Charmander's tail, but Chimchar's flame goes out when they go to sleep, although, the tail burns weaker when Chimchar is feeling under the weather. Like regular monkeys, Chimchar are very mischievous, but can show courage at times. Chimchar are very rare and only make their nests in cliffsides and rocky mountains.", special_abilities: "", behavior: "", evolution: "Chimchar evolves into Monferno once it reaches level 14 and into Infernape at level 36." })

#pokemon3 = CreatePokemons.create! ( { name: "Piplup", pokemontype: "Water", region: "Sinnoh", physiology: "Piplup is a light-blue penguin-like Pokémon, which is covered in thick down to insulate against the cold. It has a dark blue head with a primarily white face and a short, yellow beak. The dark blue feathers on its head extend down its back and around its neck, which causes it to appear to be wearing a cape. There are two white ovals on its chest and a small, light-blue marking resembles a crown above its beak. It has flipper-like arms and yellow feet with three toes each.", special_abilities: "", behavior: "Piplup has a strong sense of self-esteem. It seldom accepts food that people give because of its pride.", evolution: "Piplup evolves into Prinplup at Lv 16, which then evolves into Empoleon at Lv. 36." })

#pokemonX = CreatePokemons.create! ( { name: "Emolga", pokemontype: "Eletric/Flying", region: "Unova", physiology: "Emolga is a mammalian flying squirrel-like Pokémon that resembles Pichu, Pikachu, Plusle, Minun and Pachirisu. It has white fur on its face and the front side of its body. The back of Emolga's head is black. Its two large ears are yellow with white centers. Emolga's stubby forearms have three fingers on each hand. Its membrane is used to glide and store energy produced in its cheeks. This membrane is black on the back of its body and yellow on the front. Emolga is an expert glider especially around trees or fleeing from danger. Its legs are very short and it has small oval-shaped feet without toes, similar to Plusle and Minun. Its tail is long and jagged; the base is yellow and the rest is black.", special_abilities: "", behavior: "", evolution: "Emolga does not evolve." })

#pokemonX = CreatePokemons.create! ( { name: "Gigalith", pokemontype: "Rock", region: "Unova", physiology: "Gigalith is a massive boulder-like Pokémon that resembles a golem and a stalagmite. Its entire body is made of deep bluish gray rock. It has bright red crystals protruding from all over its body. On its face, two sharp crystals protrude from the sides of its mouth like tusks. Its four limbs are bulky and powerfully-built. It has fierce-looking deep-set yellow and red eyes.", special_abilities: "None", behavior: "", evolution: "Gigalith is the evolved form of Boldore by trade. Gigalith is the final evolution of Roggenrola.", image_url: "https://vignette2.wikia.nocookie.net/pokemon/images/5/59/526Gigalith.png/revision/latest?cb=20140329045352" })

#pokemonX = CreatePokemons.create! ( { name: "Treecko", pokemontype: “Grass”, region: "Hoenn", physiology: "Treecko are small, bipedal, lizard-like Pokémon. They have two dark green, leaf-like tails, and a red underside, similar to its evolutions Grovyle, and Sceptile. Each of its hands and feet have three digits. It has bright yellow eyes and skinny reptilian pupils. The bottom of its feet are sticky, enabling them to cling to things. ", special_abilities: "All Treecko, and all Grass-type starters, have the ability Overgrow, which allows it to use Grass-type moves at 50% additional damage if its HP is below 33%. In the Dream World, Treecko's ability Unburden doubles its speed in battle once it's held berry is consumed, assuming it is holding a berry. Tiny spikes located on each of Treecko's digits allows it to stick to and climb walls with ease.", behavior: "Treecko evolves into Grovyle once it reaches level 16. Grovyle evolves at level 36 into Sceptile.", evolution: "" })


#pokemonX = CreatePokemons.create! ( { name: "Torchic", pokemontype: "Fire", region: "Hoenn", physiology: "Torchic is a small, chick-like Pokémon. Its soft, fluffy plumage is mainly bright orange, with tiny, yellow, developing wings, and a yellow plume of three feathers atop its head. It has a small, tan beak, and large, black eyes. It has tan-colored talons with three digits. Male Torchics have a black spot on their back, but it's a little hard to see it.", special_abilities: "Torchic has a fireball blazing inside its belly. When hugged, it fills its trainer with soothing warmth, as if they are holding a hot-water bottle. It can use the flame in its belly to exhale orbs of searing fire at its opponents. The fireballs that Torchic spits are of 1,800 degrees F, leaving its foes utterly scorched.", behavior: "Torchic is very loyal and dependent on its Trainer, following behind him (or her) everywhere he (or she) would go.", evolution: "Torchic evolves into Combusken at level 16 and then i
#nto Blaziken at level 36.", image_url: "https://vignette3.wikia.nocookie.net/pokemon/images/9/91/255Torchic.png/revision/latest?cb=20140629185947" })


#pokemonX = CreatePokemons.create! ( { name: "Mudkip", pokemontype: “Water”, region: “Hoenn”, physiology: "", special_abilities: "The fin on a Mudkip's head can be used for sensing air and water currents, and can discern nearby bodies of water. The fin can sense danger as well, giving Mudkip a warning. Mudkips breathe underwater using the gills on their cheeks, and their powerful tails drive them through the water quickly. Mudkip can lift big boulders. In a pinch, Mudkips will find strength enough to crush even rocks that are bigger than themselves.
#Mudkip has the ability Torrent, which will increase the power of Water-type moves in a pinch.", behavior: "When sleeping, they bury themselves within the soil at the edge of the water. Mudkip and members of its evolution family dwell in swamps or other wetlands, deep inside isolated islands, due to their dislike of freshwater lakes and ponds.", evolution: "Mudkip evolves into Marshtomp at level 16, then into Swampert at level 36." })

#pokemonX = CreatePokemons.create! ( { name: "Bulbasaur", pokemontype: "Grass", region: "Kanto", physiology: "Bulbasaur resembles a small, squatting dinosaur that walks on four legs, but bears three claws on each of its feet and has no tail. It also has large, red eyes and very sharp teeth. Its skin is a light, turquoise color with dark, green spots. It has three claws on all four of its legs. Its most notable feature, however, is the aforementioned bulb on its back, which according to its entry in the Pokedex was planted there at birth.", special_abilities: "", behavior: "Bulbasaur often rests in bright places so its bulb can absorb sunlight. While it sleeps, the seed on its back catches the rays and uses the energy to grow.", evolution: "Ivysaur/Venusaur" })
