# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

pokemonX = CreatePokemons.create! ( { name: "Turtwig", pokemontype: "Grass", region: "Sinnoh", physiology: "Turtwig is a Pokémon and appears to be a green-ish Pokémon with a small twig on its head. On the twig are two green leaves. It has large yellow eyes and its face is oddly shaped. On the bottom of the face there is a yellow mouth in an obtuse shape. Also on its face it has two tiny nostrils. It has four small stubby feet, so it can't move as fast, and on the bottom of its feet are an obtuse area of yellow towards the bottom of the feet. It also has a shell on its back. The shell is brown with black line on the bottom and a few stripes.", :special_abilities "", :behavior "", evolution: "Turtwig evolves into a Grotle starting at level 18, which later evolves into a Torterra starting at level 32.", image_url: "https://vignette1.wikia.nocookie.net/pokemon/images/5/5c/387Turtwig.png/revision/latest?cb=20141229230435" })

pokemonX = CreatePokemons.create! ( { name: "Chimchar", pokemontype: "Fire", region: "Sinnoh", physiology: "Chimchar are based on monkeys. Being very agile, Chimchar are able to climb the rocky ledges of tall mountains, where they live. A Chimchar's flame is produced by burning gas in its stomach. Chimchar have a light colored stomach with a little swirl at the top on its chest. The swirl on Chimchar's chest carries over to Monferno and Infernape. The flames do not go out in the rain like the flames on a Charmander's tail, but Chimchar's flame goes out when they go to sleep, although, the tail burns weaker when Chimchar is feeling under the weather. Like regular monkeys, Chimchar are very mischievous, but can show courage at times. Chimchar are very rare and only make their nests in cliffsides and rocky mountains.", :special_abilities "", :behavior "", evolution: "Chimchar evolves into Monferno once it reaches level 14 and into Infernape at level 36.", image_url: "https://vignette3.wikia.nocookie.net/pokemon/images/7/76/390Chimchar.png/revision/latest?cb=20141229230356" })

pokemonX = CreatePokemons.create! ( { name: "Piplup", pokemontype: "Water", region: "Sinnoh", physiology: "Piplup is a light-blue penguin-like Pokémon, which is covered in thick down to insulate against the cold. It has a dark blue head with a primarily white face and a short, yellow beak. The dark blue feathers on its head extend down its back and around its neck, which causes it to appear to be wearing a cape. There are two white ovals on its chest and a small, light-blue marking resembles a crown above its beak. It has flipper-like arms and yellow feet with three toes each.", :special_abilities "", :behavior "Piplup has a strong sense of self-esteem. It seldom accepts food that people give because of its pride.", evolution: "Piplup evolves into Prinplup at Lv 16, which then evolves into Empoleon at Lv. 36.", image_url: "https://vignette3.wikia.nocookie.net/pokemon/images/b/b1/393Piplup.png/revision/latest?cb=20141229230319" })
